import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { CrpManifest } from "../manifest/types";
import type { Routes } from "./injection";
import { buildInjection } from "./injection";

export const CODEX_INSTRUCTIONS_PATH = join(".codex", "instructions.md");
export const CODEX_INSTRUCTIONS_MARKER_START = "<!-- CRP_INJECT_START -->";
export const CODEX_INSTRUCTIONS_MARKER_END = "<!-- CRP_INJECT_END -->";

export interface CodexInstructionsUpdateResult {
	created: boolean;
	updated: boolean;
}

export function generateCodexInstructionsContent(
	routes: Routes,
	manifest: CrpManifest,
): string {
	const projectName = manifest.project?.name ?? "project";
	const maxTokens = manifest.crp?.session_inject?.max_tokens ?? 300;
	const injection = buildInjection(routes, maxTokens);

	return [
		`# ${projectName} - Codex Instructions`,
		"",
		"Formal routing is generated by CRISP. Re-read this file at the start of each task and after context compaction.",
		"Use context-mode or sandboxed commands for bulk analysis, searches, counts, and summaries so raw project data stays out of the active conversation.",
		"",
		CODEX_INSTRUCTIONS_MARKER_START,
		injection.text.trimEnd(),
		CODEX_INSTRUCTIONS_MARKER_END,
		"",
	].join("\n");
}

export function updateCodexInstructions(
	projectDir: string,
	routes: Routes,
	manifest: CrpManifest,
): CodexInstructionsUpdateResult {
	const instructionsPath = join(projectDir, CODEX_INSTRUCTIONS_PATH);
	const nextContent = generateCodexInstructionsContent(routes, manifest);

	mkdirSync(join(projectDir, ".codex"), { recursive: true });

	if (!existsSync(instructionsPath)) {
		writeFileSync(instructionsPath, nextContent, "utf-8");
		return { created: true, updated: false };
	}

	const existing = readFileSync(instructionsPath, "utf-8");
	if (existing === nextContent) {
		return { created: false, updated: false };
	}

	writeFileSync(instructionsPath, nextContent, "utf-8");
	return { created: false, updated: true };
}
