import { existsSync, mkdirSync, renameSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { cmdCrpInit } from "../../commands/crp-init";
import { loadManifest, saveManifest } from "../manifest/io";
import type { CrpConfig, CrpManifest } from "../manifest/types";

const LEGACY_SHELL_FILES = [
	".claude/CLAUDE.md",
	".claude/GEMINI.md",
	".cursor/rules/workflow.mdc",
	".codex/instructions.md",
];

const LEGACY_MANIFEST_KEYS = [
	"knowledge_graph",
	"budget_audit",
	"context_pressure",
	"quality_scoring",
];

export interface LegacyDetection {
	isLegacy: boolean;
	legacyKeys: string[];
	legacyFiles: string[];
}

export interface MigrationReport {
	migrated: string[];
	deprecated: string[];
	backedUp: string[];
	needsManual: string[];
}

export function detectLegacyProject(
	projectDir: string = process.cwd(),
): LegacyDetection {
	const manifestPath = join(projectDir, "crp.yaml");
	const legacyKeys: string[] = [];
	const legacyFiles: string[] = [];

	if (existsSync(manifestPath)) {
		const manifest = loadManifest(manifestPath);
		for (const key of LEGACY_MANIFEST_KEYS) {
			if (key in manifest) {
				legacyKeys.push(key);
			}
		}
	}

	for (const file of LEGACY_SHELL_FILES) {
		if (existsSync(join(projectDir, file))) {
			legacyFiles.push(file);
		}
	}

	// Parent gateway generated by old sync
	if (existsSync(join(projectDir, ".claude", "skills", "SKILL.md"))) {
		legacyFiles.push(".claude/skills/SKILL.md");
	}

	return {
		isLegacy: legacyKeys.length > 0 || legacyFiles.length > 0,
		legacyKeys,
		legacyFiles,
	};
}

export function generateMigrationReport(
	projectDir: string = process.cwd(),
): MigrationReport {
	const detection = detectLegacyProject(projectDir);
	const migrated: string[] = [];
	const deprecated: string[] = [];
	const backedUp: string[] = [];
	const needsManual: string[] = [];

	if (detection.legacyKeys.includes("knowledge_graph")) {
		migrated.push("knowledge_graph → crp.kg");
	}
	if (detection.legacyKeys.includes("budget_audit")) {
		deprecated.push("budget_audit (use 'crp audit' instead)");
	}
	if (detection.legacyKeys.includes("context_pressure")) {
		deprecated.push("context_pressure (not supported in v3)");
	}
	if (detection.legacyKeys.includes("quality_scoring")) {
		deprecated.push("quality_scoring (not supported in v3)");
	}

	for (const file of detection.legacyFiles) {
		backedUp.push(`${file} → ${file}.bak.v1`);
	}

	if (!existsSync(join(projectDir, ".crp"))) {
		needsManual.push("Run 'crp init' after migration to create v3 directories");
	}

	return { migrated, deprecated, backedUp, needsManual };
}

function buildV3Config(manifest: Partial<CrpManifest>): CrpConfig {
	const v3Config: CrpConfig = {
		version: 3,
		session_inject: { max_tokens: 300, include_kg_index: true },
		tiers: { inline_threshold: 0.5, hint_threshold: 0.1 },
		telemetry: { window_days: 30 },
		kg: { max_query_tokens: 200, index_inline_tokens: 50 },
	};

	// Map knowledge_graph settings if present
	if (manifest.knowledge_graph?.enabled) {
		v3Config.kg.max_query_tokens =
			manifest.knowledge_graph.max_tokens_execution ?? 200;
	}

	return v3Config;
}

export interface MigrationResult {
	success: boolean;
	report: MigrationReport;
}

export function runMigration(
	projectDir: string = process.cwd(),
	options: { dryRun?: boolean; apply?: boolean } = {},
): MigrationResult {
	const detection = detectLegacyProject(projectDir);
	if (!detection.isLegacy) {
		console.log(
			"No legacy v1 artifacts detected. Project appears to be v3 already.",
		);
		return {
			success: true,
			report: { migrated: [], deprecated: [], backedUp: [], needsManual: [] },
		};
	}

	const report = generateMigrationReport(projectDir);

	if (!options.apply) {
		console.log("== CRP v1 → v3 Migration Report (dry run) ==");
		console.log("");
		if (report.migrated.length) {
			console.log("Migrated:");
			for (const item of report.migrated) console.log(`  [→] ${item}`);
			console.log("");
		}
		if (report.deprecated.length) {
			console.log("Deprecated:");
			for (const item of report.deprecated) console.log(`  [-] ${item}`);
			console.log("");
		}
		if (report.backedUp.length) {
			console.log("Backed up:");
			for (const item of report.backedUp) console.log(`  [↶] ${item}`);
			console.log("");
		}
		if (report.needsManual.length) {
			console.log("Manual:");
			for (const item of report.needsManual) console.log(`  [!] ${item}`);
			console.log("");
		}
		console.log("Use --apply to execute migration.");
		return { success: true, report };
	}

	// Apply migration
	// 1. Backup legacy files
	for (const file of detection.legacyFiles) {
		const src = join(projectDir, file);
		const dst = `${src}.bak.v1`;
		if (existsSync(src) && !existsSync(dst)) {
			renameSync(src, dst);
		}
	}

	// 2. Transform manifest
	const manifestPath = join(projectDir, "crp.yaml");
	const manifest: Partial<CrpManifest> = existsSync(manifestPath)
		? loadManifest(manifestPath)
		: {};

	manifest.crp = buildV3Config(manifest);

	// Remove legacy keys
	for (const key of LEGACY_MANIFEST_KEYS) {
		delete (manifest as Record<string, unknown>)[key];
	}

	const updatedManifest = manifest as CrpManifest;
	saveManifest(manifestPath, updatedManifest);

	// 3. Ensure .crp/crp.yaml exists so crp init doesn't overwrite with defaults
	const crpDir = join(projectDir, ".crp");
	mkdirSync(crpDir, { recursive: true });
	const crpYamlPath = join(crpDir, "crp.yaml");
	if (!existsSync(crpYamlPath)) {
		writeFileSync(crpYamlPath, "", "utf-8");
	}
	saveManifest(crpYamlPath, updatedManifest);

	// 4. Run crp init to create v3 structure (hooks, routes.json, etc.)
	cmdCrpInit();

	console.log("[CRP] Migration applied successfully.");
	console.log("  Legacy files backed up with .bak.v1 suffix");
	console.log("  crp.yaml updated with v3 configuration");
	console.log("  Run 'crp sync' to generate initial routes.");

	return { success: true, report };
}
