import { copyFileSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { printOk, printWarn } from "../lib/cli/format";
import { updateClaudeMd } from "../lib/crp/claude-md";
import { updateCodexInstructions } from "../lib/crp/codex-instructions";
import { TEMPLATES_DIR } from "../lib/fs/paths";
import { getDefaultAdapter } from "../lib/hooks/adapter";
import { defaultManifest } from "../lib/manifest/defaults";
import { loadManifest, saveManifest } from "../lib/manifest/io";
import type { CrpManifest } from "../lib/manifest/types";

export interface InitOptions {
	dryRun?: boolean;
	project?: string;
	description?: string;
}

export function cmdCrpInit(options: InitOptions = {}): number {
	const projectDir = process.cwd();
	const crpDir = join(projectDir, ".crp");
	const adapter = getDefaultAdapter();

	if (options.dryRun) {
		printWarn("[DRY RUN] Would create .crp/ directory structure:");
		console.log("  .crp/routes.json");
		console.log("  .crp/kg/");
		console.log("  .crp/telemetry/");
		console.log("  .crp/hooks/");
		console.log("  .crp/cache/");
		console.log("  .crp/logs/");
		console.log(
			`  ${adapter.name === "claude-code" ? ".claude/settings.local.json" : ".claude/settings.json"}`,
		);
		console.log("  CLAUDE.md (with CRP injection block)");
		console.log("  .codex/instructions.md (with CRP injection block)");
		printWarn("[DRY RUN] Would install PostToolUse hook for telemetry");
		return 0;
	}

	// Create directory structure
	const dirs = [
		join(crpDir, "kg"),
		join(crpDir, "telemetry"),
		join(crpDir, "hooks"),
		join(crpDir, "cache"),
		join(crpDir, "logs"),
	];
	for (const dir of dirs) {
		mkdirSync(dir, { recursive: true });
	}

	// Copy post-read.mjs hook script to .crp/hooks/
	const hookSrcDir = join(TEMPLATES_DIR, "hooks");
	const hookFiles = ["post-read.mjs"];
	for (const file of hookFiles) {
		const src = join(hookSrcDir, file);
		const dst = join(crpDir, "hooks", file);
		if (existsSync(src) && !existsSync(dst)) {
			copyFileSync(src, dst);
		}
	}

	// Create initial routes.json
	const routesPath = join(crpDir, "routes.json");
	if (!existsSync(routesPath)) {
		writeFileSync(
			routesPath,
			`${JSON.stringify({ version: 3, skills: [] }, null, 2)}\n`,
			"utf-8",
		);
	}

	// Create crp.yaml if not exists
	const rootYamlPath = join(projectDir, "crp.yaml");
	let manifest: CrpManifest;
	if (!existsSync(rootYamlPath)) {
		manifest = defaultManifest(
			options.project || "my-project",
			options.description,
		);
		saveManifest(rootYamlPath, manifest);
	} else {
		manifest = loadManifest(rootYamlPath) as CrpManifest;
	}

	// Generate CLAUDE.md with initial injection block
	const routes = { version: 3, skills: [] };
	const result = updateClaudeMd(projectDir, routes, manifest);
	const codexResult = updateCodexInstructions(projectDir, routes, manifest);

	// Create .crp/README.md
	const readmePath = join(crpDir, "README.md");
	if (!existsSync(readmePath)) {
		writeFileSync(
			readmePath,
			"# .crp/ directory\n\nThis directory contains generated and runtime artifacts for CRP.\nDo not edit files here directly; they are regenerated by `crp sync`.\n",
			"utf-8",
		);
	}

	// Install hooks via adapter
	adapter.install(projectDir);

	printOk("Initialized successfully.");
	console.log("  .crp/ directory created");
	console.log(`  Hooks installed to ${adapter.settingsPath(projectDir)}`);
	if (result.created) {
		console.log("  CLAUDE.md created with CRP injection block");
	} else if (result.updated) {
		console.log("  CLAUDE.md updated with CRP injection block");
	}
	if (codexResult.created) {
		console.log("  .codex/instructions.md created with CRP injection block");
	} else if (codexResult.updated) {
		console.log("  .codex/instructions.md updated with CRP injection block");
	}
	console.log("");
	console.log("Next steps:");
	console.log("  1. Create a skill:   crp skill create <name>");
	console.log("  2. Add descriptions: Edit .claude/skills/<name>/SKILL.md");
	console.log("  3. Sync routes:      crp sync");
	console.log("  4. Check budget:     crp check");
	return 0;
}
