import { describe, expect, test } from "bun:test";
import { mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { generateParentGateway } from "../../src/lib/gateway/generator";
import { parseCommonTasks } from "../../src/lib/gateway/parser";
import type { CrpManifest } from "../../src/lib/manifest/types";

describe("parseCommonTasks", () => {
	test("valid Common Tasks table -> found=true, tasks populated", async () => {
		const dir = join(tmpdir(), `crisp-test-${Date.now()}`);
		await mkdir(dir, { recursive: true });
		const gateway = join(dir, "SKILL.md");
		await writeFile(
			gateway,
			"# Skill\n\n## Common Tasks\n| Task | Must read | Workflow |\n" +
				"|------|-----------|----------|\n" +
				"| Fix | rules | workflows/fix.md |\n",
		);
		try {
			const result = parseCommonTasks(gateway);
			expect(result.found).toBe(true);
			expect(result.tasks.length).toBe(1);
			expect(result.tasks[0].task).toBe("Fix");
			expect(result.tasks[0].reads).toBe("rules");
			expect(result.tasks[0].workflow).toBe("workflows/fix.md");
		} finally {
			await rm(dir, { recursive: true, force: true });
		}
	});

	test("missing section -> found=false, message set", async () => {
		const dir = join(tmpdir(), `crisp-test-${Date.now()}`);
		await mkdir(dir, { recursive: true });
		const gateway = join(dir, "SKILL.md");
		await writeFile(gateway, "# Skill\n\nNo common tasks here.\n");
		try {
			const result = parseCommonTasks(gateway);
			expect(result.found).toBe(false);
			expect(result.tasks).toEqual([]);
			expect(result.message).toContain("Common Tasks");
		} finally {
			await rm(dir, { recursive: true, force: true });
		}
	});

	test("empty table -> found=true, tasks empty", async () => {
		const dir = join(tmpdir(), `crisp-test-${Date.now()}`);
		await mkdir(dir, { recursive: true });
		const gateway = join(dir, "SKILL.md");
		await writeFile(
			gateway,
			"# Skill\n\n## Common Tasks\n| Task | Must read | Workflow |\n" +
				"|------|-----------|----------|\n",
		);
		try {
			const result = parseCommonTasks(gateway);
			expect(result.found).toBe(true);
			expect(result.tasks).toEqual([]);
			expect(result.message).toBe("");
		} finally {
			await rm(dir, { recursive: true, force: true });
		}
	});

	test("missing file -> found=false", () => {
		const result = parseCommonTasks("/nonexistent/SKILL.md");
		expect(result.found).toBe(false);
		expect(result.message).toContain("File not found");
	});
});

describe("generateParentGateway", () => {
	test("produces correct markdown with banner", () => {
		const manifest: CrpManifest = {
			project: { name: "TestProject" },
			skills: [{ name: "backend", description: "API work" }],
			default_skill: "backend",
		};
		const output = generateParentGateway(manifest);
		expect(output).toContain("GENERATED BY CRP");
		expect(output).toContain("TestProject");
		expect(output).toContain("backend");
		expect(output).toContain("backend/SKILL.md");
		expect(output).toContain("*"); // default skill marker
	});

	test("handles empty skills list", () => {
		const manifest: CrpManifest = {
			project: { name: "EmptyProject" },
			skills: [],
		};
		const output = generateParentGateway(manifest);
		expect(output).toContain("GENERATED BY CRP");
		expect(output).toContain("EmptyProject");
		expect(output).toContain("| Skill | Description | Entry | Default |");
	});
});
