import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { generateParentGateway } from "../gateway/generator";
import { extractSkillFrontmatter } from "../manifest/frontmatter";
import { loadManifest, validateManifest } from "../manifest/io";
import type { CrpManifest, SkillEntry } from "../manifest/types";
import { emitFull } from "./checker";

function readFileSafe(path: string): string {
	try {
		return readFileSync(path, "utf-8");
	} catch {
		return "";
	}
}

function extractMarkdownTableRows(
	content: string,
	requiredHeaders: string[],
): Record<string, string>[] {
	const lines = content.split("\n");
	const headerPattern = /^\|.*\|$/;
	const normHeaders = requiredHeaders.map((h) =>
		h.replace(/[^a-z0-9]/g, "").toLowerCase(),
	);

	for (let i = 0; i < lines.length; i++) {
		const stripped = lines[i].trim();
		if (!headerPattern.test(stripped)) continue;

		let cells = stripped.split("|").map((c) => c.trim());
		cells = cells.filter((c) => c);
		const normCells = cells.map((c) =>
			c.replace(/[^a-z0-9]/g, "").toLowerCase(),
		);

		if (normCells.join("|") !== normHeaders.join("|")) continue;
		if (i + 1 >= lines.length) return [];

		const rows: Record<string, string>[] = [];
		for (let j = i + 2; j < lines.length; j++) {
			const rowLine = lines[j].trim();
			if (!rowLine.startsWith("|")) break;

			let rawCells = rowLine.split("|");
			if (rawCells[0] === "") rawCells = rawCells.slice(1);
			if (rawCells[rawCells.length - 1] === "")
				rawCells = rawCells.slice(0, -1);
			const rowCells = rawCells.map((c) => c.trim());
			if (rowCells.every((c) => /^[\s\-:]+$/.test(c))) continue;

			if (rowCells.length >= requiredHeaders.length) {
				const row: Record<string, string> = {};
				for (let k = 0; k < requiredHeaders.length; k++) {
					row[requiredHeaders[k]] = rowCells[k];
				}
				rows.push(row);
			} else {
				break;
			}
		}
		return rows;
	}
	return [];
}

export function checkManifestDrift(crpYamlPath: string): string[] {
	let manifest: CrpManifest;
	try {
		manifest = loadManifest(crpYamlPath) as CrpManifest;
	} catch {
		return [];
	}

	const errors = validateManifest(manifest);
	for (const err of errors) {
		emitFull(
			"ERROR",
			`crp.yaml validation: ${err}`,
			"Malformed manifest causes unpredictable tool behavior",
			"Fix the schema error in crp.yaml",
		);
	}

	const skillsDir = join(".claude", "skills");
	const declaredSkills = new Set(
		(manifest.skills || []).map((s: SkillEntry) => s.name),
	);
	const actualSkills = new Set<string>();

	if (existsSync(skillsDir)) {
		let entries: string[];
		try {
			entries = readdirSync(skillsDir);
		} catch {
			return [];
		}
		for (const entry of entries) {
			try {
				const st = statSync(join(skillsDir, entry));
				if (st.isDirectory() && entry !== "shared" && entry !== "SKILL.md") {
					actualSkills.add(entry);
				}
			} catch {}
		}
	}

	const drifted: string[] = [];

	for (const name of declaredSkills) {
		const sdir = join(skillsDir, name);
		if (!existsSync(sdir)) {
			emitFull(
				"ERROR",
				`Skill '${name}' declared in crp.yaml but directory not found: ${sdir}`,
				"Sync and check will fail for this skill",
				`Run \`crp skill create ${name}\` or remove from crp.yaml`,
			);
			drifted.push(sdir);
		}
	}

	for (const name of actualSkills) {
		if (!declaredSkills.has(name)) {
			emitFull(
				"INFO",
				`Undeclared skill directory found: ${join(skillsDir, name)}`,
				"Manifest does not reflect actual project structure",
				`Run \`crp skill create ${name}\` to register, or delete the directory`,
			);
		}
	}

	return drifted;
}

export function checkParentGatewayDrift(manifest: CrpManifest): string[] {
	const parentGateway = join(".claude", "skills", "SKILL.md");
	if (!existsSync(parentGateway)) {
		emitFull(
			"ERROR",
			"Parent gateway missing: .claude/skills/SKILL.md",
			"CRP routing table unavailable to agents",
			"Run `crp sync` to generate the parent gateway",
		);
		return [parentGateway];
	}

	const expectedContent = generateParentGateway(manifest);
	const actualContent = readFileSafe(parentGateway);

	if (!actualContent.includes("GENERATED BY CRP")) {
		emitFull(
			"WARNING",
			"Parent gateway may be manually edited (missing GENERATED banner)",
			"Manual edits will be overwritten on next sync",
			"Run `crp sync` to regenerate from manifest",
		);
	}

	const expectedRows = extractMarkdownTableRows(expectedContent, [
		"Skill",
		"Description",
		"Entry",
		"Default",
	]);
	const actualRows = extractMarkdownTableRows(actualContent, [
		"Skill",
		"Description",
		"Entry",
		"Default",
	]);

	const expectedBySkill = new Map(expectedRows.map((r) => [r.Skill, r]));
	const actualBySkill = new Map(actualRows.map((r) => [r.Skill, r]));

	const drifted: string[] = [];

	for (const [name, expRow] of expectedBySkill) {
		if (!actualBySkill.has(name)) {
			emitFull(
				"WARNING",
				`Skill '${name}' missing from parent gateway table`,
				`Agents won't see routing for '${name}'`,
				"Run `crp sync` to regenerate the parent gateway",
			);
			drifted.push(parentGateway);
		} else {
			const actRow = actualBySkill.get(name);
			if (actRow && expRow.Description !== actRow.Description) {
				emitFull(
					"WARNING",
					`Skill '${name}' description mismatch in parent gateway`,
					`Expected '${expRow.Description}', found '${actRow.Description}'`,
					"Run `crp sync` to regenerate from frontmatter",
				);
				drifted.push(parentGateway);
			}
		}
	}

	for (const name of actualBySkill.keys()) {
		if (!expectedBySkill.has(name)) {
			emitFull(
				"WARNING",
				`Extra skill '${name}' in parent gateway not declared in manifest`,
				"Manifest and gateway are out of sync",
				"Add to crp.yaml or remove the skill directory",
			);
			drifted.push(parentGateway);
		}
	}

	const defaultSkill = manifest.default_skill;
	if (defaultSkill && !actualContent.includes(`${defaultSkill}`)) {
		emitFull(
			"WARNING",
			`Default skill '${defaultSkill}' not referenced in parent gateway`,
			"Default routing rule may be missing",
			"Run `crp sync` to regenerate",
		);
		drifted.push(parentGateway);
	}

	return drifted;
}

export function checkEntryProxyDrift(manifest: CrpManifest): string[] {
	const skills = manifest.skills || [];
	if (skills.length <= 1) return [];

	const proxyFiles: Record<string, string> = {
		claude: join(".claude", "CLAUDE.md"),
		gemini: join(".claude", "GEMINI.md"),
		codex: join(".codex", "instructions.md"),
		cursor: join(".cursor", "rules", "workflow.mdc"),
	};

	const declaredNames = new Set(skills.map((s: SkillEntry) => s.name));
	const drifted: string[] = [];

	for (const [, proxyPath] of Object.entries(proxyFiles)) {
		if (!existsSync(proxyPath)) {
			emitFull(
				"WARNING",
				`Entry proxy missing: ${proxyPath}`,
				`${proxyPath} users won't have skill routing`,
				"Run `crp sync` to generate entry proxies",
			);
			drifted.push(proxyPath);
			continue;
		}

		const actualContent = readFileSafe(proxyPath);
		const actualRows = extractMarkdownTableRows(actualContent, [
			"Skill",
			"Description",
			"Entry",
		]);
		const actualBySkill = new Map(actualRows.map((r) => [r.Skill, r]));

		for (const name of declaredNames) {
			if (!actualBySkill.has(name)) {
				emitFull(
					"WARNING",
					`Entry proxy ${proxyPath} missing skill route: ${name}`,
					`${proxyPath} users won't see '${name}' skill`,
					"Run `crp sync` to regenerate entry proxies",
				);
				drifted.push(proxyPath);
			}
		}

		for (const name of actualBySkill.keys()) {
			if (!declaredNames.has(name)) {
				emitFull(
					"WARNING",
					`Entry proxy ${proxyPath} has extra skill route: ${name}`,
					"Proxy contains skill not declared in manifest",
					"Remove from proxy or add to crp.yaml",
				);
				drifted.push(proxyPath);
			}
		}
	}

	return drifted;
}

export function checkDescriptionConsistency(manifest: CrpManifest): string[] {
	const skills = manifest.skills || [];
	const drifted: string[] = [];

	for (const skill of skills) {
		const crpDesc = skill.description || "";
		if (!crpDesc) continue;

		const skillDir = join(".claude", "skills", skill.name);
		const frontmatter = extractSkillFrontmatter(skillDir);
		const fmDesc = (frontmatter.description as string) || "";

		if (crpDesc !== fmDesc) {
			emitFull(
				"INFO",
				`Skill '${skill.name}' description in crp.yaml differs from SKILL.md frontmatter`,
				`crp.yaml says '${crpDesc}', frontmatter says '${fmDesc}'`,
				"Remove description from crp.yaml (source of truth is frontmatter) or update frontmatter",
			);
			drifted.push(join(skillDir, "SKILL.md"));
		}
	}

	return drifted;
}

export function runAllDriftChecks(
	crpYamlPath: string,
	fix: boolean = false,
): string[] {
	let manifest: CrpManifest;
	try {
		manifest = loadManifest(crpYamlPath) as CrpManifest;
	} catch {
		console.log("ERROR: Could not load crp.yaml");
		return [];
	}

	const driftedFiles: string[] = [];
	driftedFiles.push(...checkManifestDrift(crpYamlPath));
	driftedFiles.push(...checkParentGatewayDrift(manifest));
	driftedFiles.push(...checkEntryProxyDrift(manifest));
	driftedFiles.push(...checkDescriptionConsistency(manifest));

	if (fix && driftedFiles.length > 0) {
		const unique = [...new Set(driftedFiles)].sort();
		console.log(`\n== Fix Mode: ${unique.length} drifted file(s) ==`);
		for (const f of unique) console.log(`  - ${f}`);
		console.log("\nRun `crp sync` to regenerate all drifted files.");
	}

	return [...new Set(driftedFiles)];
}
