"""crp_gateway.py — Common Tasks parser and parent gateway generator for CRP."""

from __future__ import annotations

import re
from pathlib import Path
from typing import NamedTuple

from crp_manifest import extract_skill_frontmatter


class ParseResult(NamedTuple):
    """Structured result from parsing a Common Tasks table."""

    found: bool
    tasks: list[dict]
    message: str = ""


def parse_common_tasks(gateway_path: Path) -> ParseResult:
    """Extract the Common Tasks markdown table from gateway.md."""
    content = gateway_path.read_text(encoding="utf-8")

    match = re.search(
        r"##\s+Common Tasks.*?(\n##\s|\Z)",
        content,
        re.DOTALL | re.IGNORECASE,
    )
    if not match:
        return ParseResult(
            found=False,
            tasks=[],
            message=f"Could not find 'Common Tasks' section in {gateway_path}",
        )

    section = match.group(0)
    lines = [ln for ln in section.splitlines() if ln.strip().startswith("|")]

    data_rows = []
    for line in lines:
        if re.search(r"\|[\s\-:]+\|", line) and not re.search(r"[a-zA-Z]", line):
            continue
        cells = [c.strip() for c in line.split("|")]
        cells = [c for c in cells if c]
        if len(cells) >= 3 and cells[0].lower() not in ("task", "<!-- fill:"):
            data_rows.append(
                {
                    "task": cells[0],
                    "reads": cells[1],
                    "workflow": cells[2],
                }
            )
    return ParseResult(found=True, tasks=data_rows)


def generate_parent_gateway(manifest: dict) -> str:
    """Generate the parent gateway SKILL.md content from manifest + child frontmatters."""
    project_name = manifest.get("project", {}).get("name", "Project")
    skills = manifest.get("skills", [])

    lines = [
        "<!-- GENERATED BY CRP — DO NOT EDIT THIS FILE -->",
        "<!-- Run `crp sync` to regenerate -->",
        "",
        f"# {project_name} — CRP Skill Router",
        "",
        "## Available Skills",
        "",
        "| Skill | Description | Entry | Default |",
        "|-------|-------------|-------|---------|",
    ]

    for skill in skills:
        name = skill["name"]
        skill_dir = Path(f".claude/skills/{name}")
        frontmatter = extract_skill_frontmatter(skill_dir)
        desc = frontmatter.get("description", "")
        desc = desc.split("\n")[0].strip()
        if desc.startswith("<!--"):
            desc = ""
        default_marker = "*" if name == manifest.get("default_skill") else ""
        lines.append(f"| {name} | {desc} | `{name}/SKILL.md` | {default_marker} |")

    lines += [
        "",
        "## Auto-Route Rule",
        "",
        "1. **Read `.claude/skills/SKILL.md` first** on every new task.",
        "2. Match task intent to the skill descriptions above.",
        "3. Read the matched skill's `SKILL.md` for task-level routing (Common Tasks).",
        "4. If ambiguous, use the default skill (marked *).",
        "",
        "## Session Discipline",
        "",
        "- Never skip re-reading this file — context compresses between tasks.",
        "- Skill-level routing must happen before task-level routing.",
        "",
    ]
    return "\n".join(lines)
