import { join } from "node:path";
import { extractSkillFrontmatter } from "../manifest/frontmatter";
import type { CrpManifest } from "../manifest/types";

export function generateParentGateway(manifest: CrpManifest): string {
	const projectName = manifest.project?.name || "Project";
	const skills = manifest.skills || [];

	const lines: string[] = [
		"<!-- GENERATED BY CRP — DO NOT EDIT THIS FILE -->",
		"<!-- Run `crp sync` to regenerate -->",
		"",
		`# ${projectName} — CRP Skill Router`,
		"",
		"## Available Skills",
		"",
		"| Skill | Description | Entry | Default |",
		"|-------|-------------|-------|---------|",
	];

	for (const skill of skills) {
		const skillDir = join(".claude", "skills", skill.name);
		const fm = extractSkillFrontmatter(skillDir);
		let desc = (fm.description as string) || "";
		desc = desc.split("\n")[0].trim();
		if (desc.startsWith("<!--")) desc = "";
		const marker = skill.name === manifest.default_skill ? "*" : "";
		lines.push(
			`| ${skill.name} | ${desc} | \`${skill.name}/SKILL.md\` | ${marker} |`,
		);
	}

	lines.push(
		"",
		"## Auto-Route Rule",
		"",
		"1. **Read `.claude/skills/SKILL.md` first** on every new task.",
		"2. Match task intent to the skill descriptions above.",
		"3. Read the matched skill's `SKILL.md` for task-level routing (Common Tasks).",
		"4. If ambiguous, use the default skill (marked *).",
		"",
		"## Session Discipline",
		"",
		"- Never skip re-reading this file — context compresses between tasks.",
		"- Skill-level routing must happen before task-level routing.",
		"",
	);

	return lines.join("\n");
}
