import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

function skipFrontmatter(lines: string[]): number {
	if (!lines.length || lines[0].trim() !== "---") return 0;
	for (let i = 1; i < lines.length; i++) {
		if (lines[i].trim() === "---") return i + 1;
	}
	return 0;
}

export function extractSummary(content: string, maxLines: number = 3): string {
	const match = content.match(/<!--\s*@summary:\s*(.+?)\s*-->/s);
	if (match) return match[1].trim().split("\n")[0].slice(0, 200);

	const lines = content.split("\n");
	const startIdx = skipFrontmatter(lines);
	const paragraphLines: string[] = [];
	for (const line of lines.slice(startIdx)) {
		if (line.trim().startsWith("#")) continue;
		if (line.trim()) {
			paragraphLines.push(line.trim());
			if (paragraphLines.length >= maxLines) break;
		} else if (paragraphLines.length) {
			break;
		}
	}
	return paragraphLines.join(" ").slice(0, 200);
}

export function extractHotCache(
	skillMdPath: string,
	maxLines: number = 50,
): string {
	let content: string;
	try {
		content = readFileSync(skillMdPath, "utf-8");
	} catch {
		return "";
	}
	const lines = content.split("\n");
	const startIdx = skipFrontmatter(lines);

	let endIdx = lines.length;
	for (let i = startIdx; i < lines.length; i++) {
		if (lines[i].trim() === "<!-- @hot-cache-end -->") {
			endIdx = i;
			break;
		}
	}

	const cacheLines = lines.slice(startIdx, endIdx).filter((l) => l.trim());
	return cacheLines.slice(0, maxLines).join("\n");
}

export function extractHotCacheFromDir(
	skillDir: string,
	maxLines: number = 50,
): string[] {
	const caches: string[] = [];

	const skillMd = join(skillDir, "SKILL.md");
	const cache = extractHotCache(skillMd, maxLines);
	if (cache.trim()) caches.push(cache);

	let entries: string[];
	try {
		entries = readdirSync(skillDir, { recursive: true }) as string[];
	} catch {
		return caches;
	}

	for (const entry of entries) {
		if (!entry.endsWith(".md") || entry.endsWith("SKILL.md")) continue;
		const fullPath = join(skillDir, entry);
		let fileContent: string;
		try {
			fileContent = readFileSync(fullPath, "utf-8");
		} catch {
			continue;
		}
		if (fileContent.trim().startsWith("<!-- @hot-cache -->")) {
			const fileLines = fileContent
				.split("\n")
				.slice(1)
				.filter((l) => l.trim());
			if (fileLines.length) {
				caches.push(fileLines.slice(0, maxLines).join("\n"));
			}
		}
	}

	return caches;
}

export function generateHotCacheFile(
	skillDir: string,
	maxLines: number = 50,
): string {
	const caches = extractHotCacheFromDir(skillDir, maxLines);
	let combined = caches.join("\n\n---\n\n");

	const combinedLines = combined.split("\n");
	if (combinedLines.length > maxLines) {
		combined = [...combinedLines.slice(0, maxLines), "... (truncated)"].join(
			"\n",
		);
	}

	const outputPath = join(skillDir, "_hot-cache.md");
	writeFileSync(
		outputPath,
		`<!-- @hot-cache - AUTO-GENERATED by crp kg sync -->\n<!-- DO NOT EDIT - changes will be overwritten -->\n\n${combined}\n`,
		"utf-8",
	);
	return outputPath;
}

export interface DependencyMarker {
	id: string;
	strength: string;
}

export function extractDependencyMarkers(content: string): DependencyMarker[] {
	const deps: DependencyMarker[] = [];
	const pattern = /<!--\s*@depends-on:\s*([^\s]+)(?:\s+(hard|soft))?\s*-->/gi;
	for (const match of content.matchAll(pattern)) {
		deps.push({ id: match[1].trim(), strength: match[2] || "soft" });
	}
	return deps;
}

export interface TagMarker {
	name: string;
	confidence: number;
}

export function extractTagMarkers(content: string): TagMarker[] {
	const tags: TagMarker[] = [];
	const pattern = /<!--\s*@tag:\s*([^\s]+)(?:\s+([\d.]+))?\s*-->/gi;
	for (const match of content.matchAll(pattern)) {
		tags.push({
			name: match[1].trim(),
			confidence: match[2] ? parseFloat(match[2]) : 1.0,
		});
	}
	return tags;
}
